"""
geocode.py — Ryan Renner / omahahomesforsale.com
-------------------------------------------------
Reads data/full-address.csv, geocodes every unique address via the
Google Geocoding API, and writes locations.js for the map page.

Run this locally whenever you add new transactions to the CSV:
    python3 geocode.py

Requirements:
    pip install requests

Setup:
    1. Paste your Google Maps API key into API_KEY below (or set the
       GOOGLE_MAPS_KEY environment variable — that's safer for sharing).
    2. Make sure the Geocoding API is enabled in your Google Cloud project.
    3. Run the script. It will print each address as it goes.
    4. Commit the updated locations.js to GitHub — the live map updates
       automatically once GitHub Pages rebuilds (usually < 1 minute).
"""

import csv
import json
import os
import time
import requests

# ── Config ──────────────────────────────────────────────────────────────────
API_KEY   = os.environ.get("GOOGLE_MAPS_KEY", "AIzaSyCXBLD5OgD1fTy9wRsU3YHb8gt8RO22Vg8")
CSV_FILE  = os.path.join(os.path.dirname(__file__), "data", "full-address.csv")
OUT_FILE  = os.path.join(os.path.dirname(__file__), "locations.js")

# Seconds to wait between API calls (stay well under the 50 QPS limit)
REQUEST_DELAY = 0.05
# ─────────────────────────────────────────────────────────────────────────────


def clean_address(row: dict) -> str | None:
    """
    Return the best full address string from a CSV row, or None if the
    row should be skipped.
    """
    full = row.get("Full Address", "").strip().strip('"').strip(",").strip()
    street = row.get("Street Address", "").strip().strip('"').strip(",").strip()
    city   = row.get("City", "").strip()
    state  = row.get("State", "NE").strip() or "NE"

    # Prefer Full Address if it looks complete (has a digit and "NE")
    if full and full not in (",", "") and any(ch.isdigit() for ch in full):
        return full

    # Fall back to Street Address column — it sometimes holds the full address
    if street and any(ch.isdigit() for ch in street):
        # If it already contains a state abbreviation it's a complete address
        if "NE" in street or "IA" in street:
            return street
        # Otherwise append city + state
        if city:
            return f"{street} {city}, {state}"
        return f"{street}, {state}"

    return None


def geocode(address: str) -> tuple[float, float] | None:
    """Call the Google Geocoding API. Returns (lat, lng) or None on failure."""
    url = "https://maps.googleapis.com/maps/api/geocode/json"
    resp = requests.get(url, params={"address": address, "key": API_KEY}, timeout=10)
    resp.raise_for_status()
    data = resp.json()

    if data["status"] == "OK":
        loc = data["results"][0]["geometry"]["location"]
        return loc["lat"], loc["lng"]

    if data["status"] == "ZERO_RESULTS":
        print(f"  [no results] {address}")
    elif data["status"] == "OVER_QUERY_LIMIT":
        print("  [over quota] — wait and retry, or check your billing settings")
    else:
        print(f"  [{data['status']}] {address}")
    return None


def main() -> None:
    if API_KEY == "YOUR_API_KEY_HERE":
        raise SystemExit(
            "Set your API key: edit API_KEY in geocode.py or export "
            "GOOGLE_MAPS_KEY=your_key before running."
        )

    locations: list[dict] = []
    seen: set[str] = set()
    skipped = 0

    with open(CSV_FILE, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)

    print(f"Reading {len(rows)} rows from {CSV_FILE} …\n")

    for row in rows:
        address = clean_address(row)
        if not address:
            skipped += 1
            continue
        if address in seen:
            skipped += 1
            continue
        seen.add(address)

        result = geocode(address)
        if result:
            lat, lng = result
            locations.append({"lat": lat, "lng": lng, "address": address})
            print(f"  OK  {address}")
        else:
            skipped += 1

        time.sleep(REQUEST_DELAY)

    # Write output
    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by geocode.py — do not edit by hand.\n")
        fh.write("// Re-run geocode.py after adding addresses to the CSV.\n")
        fh.write("const LOCATIONS = ")
        json.dump(locations, fh, indent=2)
        fh.write(";\n")

    print(f"\nDone. {len(locations)} locations written to {OUT_FILE}")
    print(f"      {skipped} rows skipped (blank, duplicate, or unresolvable).")
    print("\nNext: commit locations.js and push to GitHub.")


if __name__ == "__main__":
    main()
