// Auto-generated by geocode.py — do not edit by hand.
// Re-run geocode.py after adding addresses to the CSV.
const LOCATIONS = [
  {
    "lat": 41.2572514,
    "lng": -95.991794,
    "address": "308 S 50th Ave Omaha, NE 68132"
  },
  {
    "lat": 41.2228207,
    "lng": -96.2438761,
    "address": "3543 South 210th St Elkhorn, NE 68022"
  },
  {
    "lat": 41.2675978,
    "lng": -95.9990402,
    "address": "723 N 57th St Omaha, NE 68132"
  },
  {
    "lat": 41.17289359999999,
    "lng": -96.1344515,
    "address": "14105 Jennifer Rd Omaha, NE 68138"
  },
  {
    "lat": 41.2587308,
    "lng": -95.9604913,
    "address": "200 S 31st Ave #4509 Omaha, NE 68131"
  },
  {
    "lat": 41.2712338,
    "lng": -95.99346369999999,
    "address": "5107 Lafayette Avenue Omaha, NE 68132"
  },
  {
    "lat": 41.313496,
    "lng": -96.161542,
    "address": "5933 N 158th Court #302 Omaha, NE 68116"
  },
  {
    "lat": 41.2870528,
    "lng": -96.0023686,
    "address": "3104 N 58th St Omaha, NE 68104"
  },
  {
    "lat": 41.2757115,
    "lng": -96.1078531,
    "address": "12330 Franklin St Omaha, NE 68154"
  },
  {
    "lat": 41.2408236,
    "lng": -95.9893371,
    "address": "1920 S 49th Ave Omaha, NE 68106"
  },
  {
    "lat": 41.2777234,
    "lng": -95.98511909999999,
    "address": "1909 N 48th St Omaha, NE 68104"
  },
  {
    "lat": 41.2515948,
    "lng": -96.087955,
    "address": "845 S 112th Plaza Omaha, NE 68154"
  },
  {
    "lat": 41.2568616,
    "lng": -95.99179559999999,
    "address": "314 S 50th Avenue Omaha , NE 68132"
  },
  {
    "lat": 40.9281057,
    "lng": -95.88013509999999,
    "address": "9305 Sterling Circle, Lot 1741 Plattsmouth, NE 68048"
  },
  {
    "lat": 41.2587308,
    "lng": -95.9604913,
    "address": "200 S 31st Avenue #4207 Omaha, NE 68131"
  },
  {
    "lat": 41.2297185,
    "lng": -96.08283759999999,
    "address": "3206 S 109th St Omaha, NE 68144"
  },
  {
    "lat": 41.2752832,
    "lng": -96.0112417,
    "address": "6420 Franklin St Omaha, NE 68104"
  },
  {
    "lat": 41.3529032,
    "lng": -96.1512741,
    "address": "10301 Rosewater Pkwy Bennington, NE 68007"
  },
  {
    "lat": 41.5497078,
    "lng": -96.1487598,
    "address": "646 N 24 St Blair, NE 68008"
  },
  {
    "lat": 41.23074570000001,
    "lng": -95.9695024,
    "address": "3111 S 38th Ave Omaha, NE 68105"
  },
  {
    "lat": 41.1158602,
    "lng": -95.9644902,
    "address": "13304 S 35th St Bellevue, NE 68123"
  },
  {
    "lat": 41.2533341,
    "lng": -96.151506,
    "address": "623 S 153 Circle Omaha, NE 68154"
  },
  {
    "lat": 41.1439755,
    "lng": -96.09382099999999,
    "address": "11517 Grissom St Papillion, NE 68046"
  },
  {
    "lat": 41.2279265,
    "lng": -95.9447177,
    "address": "2201 Deer Park Boulevard Omaha, NE 68108"
  },
  {
    "lat": 41.2368511,
    "lng": -96.05421,
    "address": "2330 S 91 Street Omaha, NE 68124"
  },
  {
    "lat": 41.2719802,
    "lng": -95.994518,
    "address": "5119 Hamilton St Omaha, NE 68132"
  },
  {
    "lat": 41.2351159,
    "lng": -96.10932679999999,
    "address": "2567 S 125th Avenue Omaha, NE 68144"
  },
  {
    "lat": 41.2542857,
    "lng": -96.1688207,
    "address": "16136 Dewey Avenue Omaha, NE 68118"
  },
  {
    "lat": 41.270495,
    "lng": -95.9687088,
    "address": "1115 N 38th Street Omaha, NE 68131"
  },
  {
    "lat": 41.3286927,
    "lng": -96.05716249999999,
    "address": "7614 N 92nd Ave Omaha, NE 68122"
  },
  {
    "lat": 41.106036,
    "lng": -96.3303546,
    "address": "735 N River Rd Ashland, NE 68003"
  },
  {
    "lat": 41.2039499,
    "lng": -96.1883711,
    "address": "17460 Renfro Street Omaha, NE 68135"
  },
  {
    "lat": 41.3262904,
    "lng": -96.03247950000001,
    "address": "7404 N 77 Terrace Omaha, NE 68122"
  },
  {
    "lat": 41.2741007,
    "lng": -96.16022240000001,
    "address": "15724 Louis Dr Omaha, NE 68118"
  },
  {
    "lat": 41.1898378,
    "lng": -95.9763408,
    "address": "7004 S 41st Avenue Omaha, NE 68147"
  },
  {
    "lat": 41.17903760000001,
    "lng": -96.20586829999999,
    "address": "8106 S 185th Circle Omaha, NE 68136"
  },
  {
    "lat": 41.2116665,
    "lng": -96.2852743,
    "address": "4809 S 236th Circle Omaha, NE 68022"
  },
  {
    "lat": 41.2361557,
    "lng": -96.1258484,
    "address": "13573 Arbor St Omaha, NE 68144"
  },
  {
    "lat": 41.2979728,
    "lng": -96.04089929999999,
    "address": "8211 Boyd St Omaha , NE 68134"
  },
  {
    "lat": 41.22674,
    "lng": -96.04960039999999,
    "address": "3503 S 87th Ave Omaha, NE 68124"
  },
  {
    "lat": 41.2511153,
    "lng": -95.97708279999999,
    "address": "4232 Mayberry St Omaha, NE 68105"
  },
  {
    "lat": 41.2012123,
    "lng": -96.1627559,
    "address": "15921 T St Omaha, NE 68135"
  },
  {
    "lat": 41.179376,
    "lng": -96.2280981,
    "address": "19868 Birch Avenue Gretna, NE 68028"
  },
  {
    "lat": 41.3042805,
    "lng": -96.11321369999999,
    "address": "5110 North 127th St Omaha, NE 68164"
  },
  {
    "lat": 41.3197011,
    "lng": -95.9494948,
    "address": "2553 Mary St Omaha, NE 68112"
  },
  {
    "lat": 41.3260047,
    "lng": -96.03643249999999,
    "address": "7335 N 80th Street Omaha, NE 68122"
  },
  {
    "lat": 41.2754268,
    "lng": -95.99385889999999,
    "address": "5132 Franklin Street Omaha, NE 68104"
  },
  {
    "lat": 40.98886410000001,
    "lng": -95.9811534,
    "address": "14407 Penny Dr Plattsmouth, NE 68048"
  },
  {
    "lat": 41.049045,
    "lng": -95.95738,
    "address": "2912 Lakeside Drive Plattsmouth, NE 68048"
  },
  {
    "lat": 41.2726985,
    "lng": -96.1463429,
    "address": "1417 N 149th Ct Omaha , NE 68154"
  },
  {
    "lat": 41.300305,
    "lng": -96.1760134,
    "address": "4548 N 167th St Omaha, NE 68116"
  },
  {
    "lat": 41.31616289999999,
    "lng": -96.0722023,
    "address": "6401 N 102 Avenue Omaha, NE 68134"
  },
  {
    "lat": 41.3251656,
    "lng": -96.03247999999999,
    "address": "7713 Wyoming St. Omaha, NE 68122"
  },
  {
    "lat": 41.11777680000001,
    "lng": -95.9778721,
    "address": "4405 Leawood Dr Bellevue, NE 68123"
  },
  {
    "lat": 41.4044841,
    "lng": -96.04780509999999,
    "address": "1814 County Road P41 Omaha, NE 68152"
  },
  {
    "lat": 41.2110301,
    "lng": -96.16256179999999,
    "address": "4806 Lakeside Drive Omaha, NE 68135"
  },
  {
    "lat": 41.2620218,
    "lng": -96.0114531,
    "address": "6403 Chicago Street Omaha, NE 68132"
  },
  {
    "lat": 41.1370024,
    "lng": -95.9630402,
    "address": "3402 E Dutchman Cir Bellevue, NE 68123"
  },
  {
    "lat": 41.2038249,
    "lng": -96.0399355,
    "address": "8107 Oakwood Street Ralston, NE 68127"
  },
  {
    "lat": 41.2180628,
    "lng": -96.25186529999999,
    "address": "4206 S 214th St Elkhorn, NE 68022"
  },
  {
    "lat": 41.3042805,
    "lng": -96.11321369999999,
    "address": "5110 N 127th Street Omaha, NE 68164"
  },
  {
    "lat": 41.1352949,
    "lng": -95.9057637,
    "address": "2302 Clay St Bellevue, NE 68005"
  },
  {
    "lat": 41.1374921,
    "lng": -96.21279179999999,
    "address": "11516 S 190th St Gretna, NE 68028"
  },
  {
    "lat": 41.2370671,
    "lng": -95.9893323,
    "address": "2322 S 49th Ave Omaha, NE 68106"
  },
  {
    "lat": 41.22504620000001,
    "lng": -96.10218069999999,
    "address": "3514 S 121st Street Omaha, NE 68144"
  },
  {
    "lat": 41.21473760000001,
    "lng": -96.1716788,
    "address": "4502 S 163rd St Omaha, NE 68135"
  },
  {
    "lat": 41.27311539999999,
    "lng": -96.20537039999999,
    "address": "1508 N 185th St Omaha, NE 68022"
  },
  {
    "lat": 41.2293523,
    "lng": -96.1689336,
    "address": "16318 Spring Cir Omaha, NE 68130"
  },
  {
    "lat": 41.3291032,
    "lng": -96.0443583,
    "address": "8461 Craig Ave Omaha, NE 68122"
  },
  {
    "lat": 41.2559917,
    "lng": -96.2057409,
    "address": "410 S 185th Street Omaha, NE 68022"
  },
  {
    "lat": 41.3049542,
    "lng": -96.2416209,
    "address": "5032 N 209th St Omaha, NE 68022"
  },
  {
    "lat": 41.2775239,
    "lng": -95.9844882,
    "address": "4720 Parker St Omaha, NE 68104"
  },
  {
    "lat": 41.1045314,
    "lng": -95.98547719999999,
    "address": "13902 S 47th St Bellevue, NE 68133"
  },
  {
    "lat": 41.276632,
    "lng": -96.2421141,
    "address": "20828 Parker Elkhorn, NE 68022"
  },
  {
    "lat": 41.2107836,
    "lng": -96.21255889999999,
    "address": "4817 S 190th St Omaha, NE 68135"
  },
  {
    "lat": 41.224763,
    "lng": -96.07963799999999,
    "address": "3630 S 107th St Omaha, NE 68124"
  },
  {
    "lat": 41.2223002,
    "lng": -96.19348749999999,
    "address": "3852 S 177th Avenue Omaha, NE 68130"
  },
  {
    "lat": 41.1045314,
    "lng": -95.98547719999999,
    "address": "13902 S 47th Street Bellevue, NE 68133"
  },
  {
    "lat": 40.83807700000001,
    "lng": -95.85879399999999,
    "address": "2192 E Lake Drive Union, NE 68455"
  },
  {
    "lat": 40.6759711,
    "lng": -96.48692380000001,
    "address": "17555 Autumn Blaze Dr Bennett, NE 68317"
  },
  {
    "lat": 41.2540852,
    "lng": -95.9310146,
    "address": "1101 Jackson Street #205 Omaha, NE 68102"
  },
  {
    "lat": 41.1628146,
    "lng": -96.02867859999999,
    "address": "1018 Haverford Drive Papillion, NE 68046"
  },
  {
    "lat": 41.2396886,
    "lng": -96.2013781,
    "address": "2111 S 183rd Cir Omaha, NE 68130"
  },
  {
    "lat": 41.358375,
    "lng": -96.180858,
    "address": "17001 Benjamin St Bennington, NE 68007"
  },
  {
    "lat": 41.2799224,
    "lng": -95.995371,
    "address": "2308 N 52nd St Omaha, NE 68104"
  },
  {
    "lat": 40.9152381,
    "lng": -95.87223859999999,
    "address": "8514 Riverdale Road Plattsmouth, NE 68048"
  },
  {
    "lat": 41.2389881,
    "lng": -96.10914609999999,
    "address": "12434 Martha St Omaha, NE 68144"
  },
  {
    "lat": 41.2176228,
    "lng": -96.2562518,
    "address": "21741 G Street Omaha, NE 68022"
  },
  {
    "lat": 41.1722797,
    "lng": -96.0110566,
    "address": "6414 Peters Parkway Papillion, NE 68157"
  },
  {
    "lat": 41.2974845,
    "lng": -96.2369183,
    "address": "20517 Taylor Street Omaha, NE 68022"
  },
  {
    "lat": 41.288579,
    "lng": -96.3330505,
    "address": "3306 N 265th Court Waterloo, NE 68069"
  },
  {
    "lat": 41.2622577,
    "lng": -95.9837708,
    "address": "4618 Wakeley Street Omaha, NE 68132"
  },
  {
    "lat": 41.1495839,
    "lng": -95.9113203,
    "address": "1145 St Andrews Road Bellevue, NE 68005"
  },
  {
    "lat": 41.1954645,
    "lng": -96.086978,
    "address": "11122 Jefferson St Omaha, NE 68137"
  },
  {
    "lat": 41.2587308,
    "lng": -95.9604913,
    "address": "200 South 31st Avenue #4612 Omaha, NE 68131"
  },
  {
    "lat": 41.313496,
    "lng": -96.161542,
    "address": "5933 N 158th Ct, #302 Omaha, NE 68116"
  },
  {
    "lat": 41.2981139,
    "lng": -96.1723153,
    "address": "16414 Taylor Street Omaha, NE 68116"
  },
  {
    "lat": 41.2794572,
    "lng": -95.99290839999999,
    "address": "2224 N 51st Street Omaha, NE 68104"
  },
  {
    "lat": 41.3101723,
    "lng": -96.1514996,
    "address": "15113 Hartman Cir Omaha, NE 68116"
  },
  {
    "lat": 41.3367298,
    "lng": -96.15789850000002,
    "address": "8464 N 155th St Bennington, NE 68007"
  },
  {
    "lat": 41.142874,
    "lng": -96.0590151,
    "address": "1111 Devon Drive Papillion, NE 68046"
  },
  {
    "lat": 41.2284245,
    "lng": -96.0930118,
    "address": "3321 S 115 Street Omaha, NE 68144"
  },
  {
    "lat": 41.1635592,
    "lng": -95.8987902,
    "address": "311 Fawn Court Bellevue, NE 68005"
  },
  {
    "lat": 41.2823212,
    "lng": -95.99538299999999,
    "address": "2524 N 52nd St. Omaha, NE 68104"
  },
  {
    "lat": 41.2099032,
    "lng": -96.0721942,
    "address": "10305 N St Omaha, NE 68127"
  },
  {
    "lat": 41.2487016,
    "lng": -95.9258504,
    "address": "707 Caniglia Plaza Omaha, NE 68108"
  },
  {
    "lat": 41.3275028,
    "lng": -96.035212,
    "address": "7906 Potter Plaza Omaha, NE 68122"
  },
  {
    "lat": 41.2568056,
    "lng": -96.1841469,
    "address": "17223 Harney St Omaha, NE 68118"
  },
  {
    "lat": 41.1669589,
    "lng": -96.0304354,
    "address": "815 Valentine Lane Papillion, NE 68046"
  },
  {
    "lat": 41.2719751,
    "lng": -95.99477499999999,
    "address": "5121 Hamilton Street Omaha, NE 68132"
  },
  {
    "lat": 41.1993523,
    "lng": -96.20813199999999,
    "address": "18704 W St Omaha, NE 68135"
  },
  {
    "lat": 41.2594884,
    "lng": -95.95978559999999,
    "address": "120 S 31st Ave, #5410 Omaha, NE 68131"
  },
  {
    "lat": 41.2963212,
    "lng": -96.1270174,
    "address": "13627 Hillsborough Dr Omaha, NE 68164"
  },
  {
    "lat": 41.2485553,
    "lng": -95.98102089999999,
    "address": "4507 Pacific St Omaha, NE 68106"
  },
  {
    "lat": 41.2467961,
    "lng": -96.1966745,
    "address": "1227 S 180th Plaza Omaha, NE 68130"
  },
  {
    "lat": 41.25138760000001,
    "lng": -95.9306072,
    "address": "1027 Marcy Plaza #303 Omaha, NE 68108"
  },
  {
    "lat": 41.3280964,
    "lng": -96.13965259999999,
    "address": "7441 N 144th Ave Bennington, NE 68007"
  },
  {
    "lat": 41.17289359999999,
    "lng": -96.1344515,
    "address": "14105 Jennifer Road Omaha, NE 68138"
  },
  {
    "lat": 41.2258043,
    "lng": -96.153959,
    "address": "15250 Ontario Street Omaha, NE 68144"
  },
  {
    "lat": 41.34923879999999,
    "lng": -95.9632491,
    "address": "9646 N 29th Street Omaha, NE 68112"
  },
  {
    "lat": 41.2820823,
    "lng": -96.0062315,
    "address": "2520 N 60th Avenue Omaha, NE 68104"
  },
  {
    "lat": 41.2304641,
    "lng": -96.1206765,
    "address": "3108 S 133rd St Omaha, NE 68144"
  },
  {
    "lat": 41.133883,
    "lng": -96.0447751,
    "address": "230 Windsor Dr Papillion, NE 68046"
  },
  {
    "lat": 41.2893749,
    "lng": -96.01893249999999,
    "address": "6795 Emmet Street Omaha, NE 68104-3127"
  },
  {
    "lat": 41.2505266,
    "lng": -96.0872509,
    "address": "924 S 111th Plaza Omaha, NE 68154"
  },
  {
    "lat": 41.2998565,
    "lng": -96.2454901,
    "address": "21125 Meredith Avenue Elkhorn, NE 68022"
  },
  {
    "lat": 41.2587308,
    "lng": -95.9604913,
    "address": "200 S 31 Avenue #4509 Omaha, NE 68131"
  },
  {
    "lat": 41.1871911,
    "lng": -95.9470284,
    "address": "2319 Josephine Street Omaha, NE 68147"
  },
  {
    "lat": 41.2580996,
    "lng": -96.052081,
    "address": "8912 Douglas Court Omaha, NE 68114"
  },
  {
    "lat": 41.25043,
    "lng": -96.2276772,
    "address": "907 S 200th St Omaha, NE 68022"
  },
  {
    "lat": 41.1894323,
    "lng": -96.1706055,
    "address": "7015 S 164th St Omaha, NE 68136"
  },
  {
    "lat": 41.3062897,
    "lng": -96.0973805,
    "address": "11760 Raleigh Drive Omaha, NE 68164"
  },
  {
    "lat": 41.2434306,
    "lng": -96.0556501,
    "address": "9168 Hickory St. Omaha, NE 68124"
  },
  {
    "lat": 41.2276297,
    "lng": -96.0790833,
    "address": "3349 S 107th St Omaha, NE 68124"
  },
  {
    "lat": 41.2748399,
    "lng": -95.98946959999999,
    "address": "4936 N Happy Hollow Blvd Omaha, NE 68104"
  },
  {
    "lat": 41.1803561,
    "lng": -96.02009989999999,
    "address": "7731 La Vista Drive La Vista, NE 68128"
  },
  {
    "lat": 41.2558089,
    "lng": -95.9969734,
    "address": "5311 Howard Street Omaha, NE 68106"
  },
  {
    "lat": 40.8821532,
    "lng": -96.7004972,
    "address": "7117 Whitewater Lane Lincoln, NE 68521"
  },
  {
    "lat": 41.3062293,
    "lng": -96.1294271,
    "address": "13752 Camden Ave Omaha, NE 68164"
  },
  {
    "lat": 41.2267634,
    "lng": -96.03377950000001,
    "address": "3519 South 78th Street Omaha, NE 68124"
  },
  {
    "lat": 41.2391485,
    "lng": -96.2603267,
    "address": "2111 S 220th Avenue Omaha, NE 68022"
  },
  {
    "lat": 41.2533087,
    "lng": -96.11076090000002,
    "address": "625 Morrison Drive Omaha, NE 68154"
  },
  {
    "lat": 41.2775239,
    "lng": -95.9844882,
    "address": "4720 Parker Street Omaha, NE 68104"
  },
  {
    "lat": 41.1679941,
    "lng": -96.06039729999999,
    "address": "648 Reeves Cir Papillion, NE 68046"
  },
  {
    "lat": 41.266934,
    "lng": -95.92483209999999,
    "address": "555 Riverfront Plaza #504 Omaha, NE 68102"
  },
  {
    "lat": 41.3307961,
    "lng": -96.18480550000001,
    "address": "8017 N 173rd St Bennington, NE 68007"
  },
  {
    "lat": 41.3118099,
    "lng": -96.05963279999999,
    "address": "9374 Laurel Ave Omaha, NE 68134"
  },
  {
    "lat": 41.2258043,
    "lng": -96.153959,
    "address": "15250 Ontario St Omaha, NE 68144"
  },
  {
    "lat": 41.2750732,
    "lng": -96.24098599999999,
    "address": "20816 Honeysuckle Drive Omaha, NE 68022"
  },
  {
    "lat": 41.1272233,
    "lng": -96.0873039,
    "address": "11217 Portage Drive Papillion, NE 68046"
  },
  {
    "lat": 40.9213818,
    "lng": -95.88456049999999,
    "address": "8833 Verdon Circle Plattsmouth, NE 68048"
  },
  {
    "lat": 41.1888251,
    "lng": -96.2034001,
    "address": "7030 S 183rd Terrace Omaha, NE 68136"
  },
  {
    "lat": 41.465264,
    "lng": -96.0581584,
    "address": "5884 High Pasture Dr Fort Calhoun, NE 68023"
  },
  {
    "lat": 41.2434282,
    "lng": -96.0887989,
    "address": "1621 S 113th Plaza Omaha, NE 68144"
  },
  {
    "lat": 40.7636557,
    "lng": -96.6789027,
    "address": "2941 Tierra Dr Lincoln, NE 68516"
  },
  {
    "lat": 41.1890364,
    "lng": -96.22399560000001,
    "address": "19747 Gertrude Street Gretna, NE 68028"
  },
  {
    "lat": 41.3016371,
    "lng": -96.1779176,
    "address": "4705 N 168th Ave Omaha, NE 68116"
  },
  {
    "lat": 41.1849825,
    "lng": -96.12324869999999,
    "address": "7513 S 135 Street Omaha, NE 68138"
  },
  {
    "lat": 41.2568616,
    "lng": -95.99179559999999,
    "address": "314 S 50th Ave Omaha, NE 68132"
  },
  {
    "lat": 40.91779409999999,
    "lng": -95.8949873,
    "address": "1019 Brock Lane Plattsmouth, NE 68048"
  },
  {
    "lat": 41.2652998,
    "lng": -95.9938013,
    "address": "5112 Underwood Ave Omaha, NE 68132"
  },
  {
    "lat": 41.25584980000001,
    "lng": -95.97098000000001,
    "address": "3855 Dewey Ave Omaha, NE 68105"
  },
  {
    "lat": 41.2732073,
    "lng": -96.1490302,
    "address": "14995 Charles Circle Omaha, NE 68154"
  },
  {
    "lat": 41.2673126,
    "lng": -95.92352509999999,
    "address": "444 Riverfront Plaza #506 Omaha, NE 68102"
  },
  {
    "lat": 41.503582,
    "lng": -96.08108109999999,
    "address": "9202 Greeley Ave Blair, NE 68008"
  },
  {
    "lat": 41.2489537,
    "lng": -96.00153670000002,
    "address": "5706 Pacific Street Omaha, NE 68106"
  },
  {
    "lat": 41.2811962,
    "lng": -96.0667869,
    "address": "9752 Cady Avenue Omaha, NE 68134"
  },
  {
    "lat": 41.3250277,
    "lng": -96.086243,
    "address": "11033 Girard St Omaha, NE 68142"
  },
  {
    "lat": 41.3268217,
    "lng": -96.03272079999999,
    "address": "7424 N 77th Terrace Omaha, NE 68122"
  },
  {
    "lat": 41.2869611,
    "lng": -96.33399,
    "address": "26610 Wirt Plaza Waterloo, NE 68069"
  },
  {
    "lat": 41.2489537,
    "lng": -96.00153670000002,
    "address": "5706 Pacific St Omaha, NE 68106"
  },
  {
    "lat": 41.1860722,
    "lng": -95.9838491,
    "address": "4514 Trail Creek Dr Omaha, NE 68157"
  },
  {
    "lat": 41.2750732,
    "lng": -96.24098599999999,
    "address": "20816 Honeysuckle Drive Elkhorn, NE 68022"
  },
  {
    "lat": 41.3242457,
    "lng": -96.1432949,
    "address": "14612 Read Circle Bennington, NE 68007"
  },
  {
    "lat": 41.339768,
    "lng": -96.0005285,
    "address": "8805 Raven Oaks Drive Omaha, NE 68152"
  },
  {
    "lat": 41.2593404,
    "lng": -95.927219,
    "address": "105 S 9th Street #510 Omaha, NE 68102"
  },
  {
    "lat": 41.2428016,
    "lng": -95.9914053,
    "address": "5023 Hickory Omaha, NE 68106"
  },
  {
    "lat": 41.3000127,
    "lng": -96.1877468,
    "address": "4504 N 174th Ave Omaha, NE 68116"
  },
  {
    "lat": 41.2673126,
    "lng": -95.92352509999999,
    "address": "444 Riverfront Plaza #507 Omaha, NE 68102"
  },
  {
    "lat": 41.2423321,
    "lng": -96.2400467,
    "address": "3919 S 207th Street Elkhorn, NE 68022"
  },
  {
    "lat": 41.2540852,
    "lng": -95.9310146,
    "address": "1101 Jackson #205 Omaha, NE 68102"
  },
  {
    "lat": 41.25803519999999,
    "lng": -95.95979179999999,
    "address": "220 S 31 Avenue #3307 Omaha, NE 68131"
  },
  {
    "lat": 41.32469409999999,
    "lng": -96.0342897,
    "address": "7184 N 78th Ct Omaha, NE 68122"
  },
  {
    "lat": 41.2592411,
    "lng": -96.0984498,
    "address": "247 N 118th St Omaha, NE 68154"
  },
  {
    "lat": 41.2643567,
    "lng": -95.99176779999999,
    "address": "5016 California Street #5 Omaha, NE 68132"
  },
  {
    "lat": 41.2622541,
    "lng": -95.97326989999999,
    "address": "326 N 40th Omaha, NE 68131"
  },
  {
    "lat": 41.2786585,
    "lng": -96.1449999,
    "address": "14812 Grant St Omaha, NE 68116"
  },
  {
    "lat": 41.3202211,
    "lng": -96.0818733,
    "address": "6721 N 108th Ave Omaha, NE 68164"
  },
  {
    "lat": 41.1951912,
    "lng": -96.2134068,
    "address": "6223 S 191 St Omaha, NE 68135"
  },
  {
    "lat": 41.1651099,
    "lng": -96.20247959999999,
    "address": "9557 S 184th Ave Omaha, NE 68136"
  },
  {
    "lat": 41.260204,
    "lng": -95.9977723,
    "address": "106 N 54 Street Omaha, NE 68132"
  },
  {
    "lat": 41.297572,
    "lng": -96.18297869999999,
    "address": "4302 N 171 Street Omaha, NE 68116"
  },
  {
    "lat": 41.3013605,
    "lng": -96.09097179999999,
    "address": "11418 Fowler Ave Omaha, NE 68164"
  },
  {
    "lat": 41.2568656,
    "lng": -95.93748889999999,
    "address": "312 S 16 Street #31 Omaha, NE 68102"
  },
  {
    "lat": 41.1775485,
    "lng": -96.2126311,
    "address": "8120 S 190 Avenue Omaha, NE 68136"
  },
  {
    "lat": 41.2680815,
    "lng": -96.02787939999999,
    "address": "907 N 74 Avenue Omaha, NE 68114"
  },
  {
    "lat": 41.2391485,
    "lng": -96.2603267,
    "address": "2111 S 220th Ave Omaha, NE 68022"
  },
  {
    "lat": 41.2527671,
    "lng": -96.01686939999999,
    "address": "721 S 67th Ave Omaha, NE 68106"
  },
  {
    "lat": 41.2292924,
    "lng": -96.165571,
    "address": "16112 Spring St Omaha, NE 68130"
  },
  {
    "lat": 41.2570665,
    "lng": -96.05313939999999,
    "address": "9009 Farnam Omaha, NE 68114"
  },
  {
    "lat": 41.2569875,
    "lng": -95.99234489999999,
    "address": "311 S 51st St Omaha, NE 68132"
  },
  {
    "lat": 41.2835894,
    "lng": -96.0667371,
    "address": "2706 N 97th Ave Omaha, NE 68134"
  },
  {
    "lat": 41.2586216,
    "lng": -96.0636444,
    "address": "9726 Ascot Drive Omaha, NE 68114"
  },
  {
    "lat": 41.050578,
    "lng": -95.95345499999999,
    "address": "2709 Fountain Circle Plattsmouth, NE 68048"
  },
  {
    "lat": 41.3189372,
    "lng": -96.1815783,
    "address": "6604 N 170th Ave Omaha, NE 68116"
  },
  {
    "lat": 41.2594884,
    "lng": -95.95978559999999,
    "address": "120 S 31st Ave #5302 Omaha, NE 68131"
  },
  {
    "lat": 41.2712338,
    "lng": -95.99346369999999,
    "address": "5107 Lafayette Ave Omaha, NE 68132"
  },
  {
    "lat": 41.3272019,
    "lng": -96.1303063,
    "address": "13912 Hanover St Omaha, NE 68142"
  },
  {
    "lat": 41.1994588,
    "lng": -96.1670221,
    "address": "16134 W Street Omaha, NE 68135"
  },
  {
    "lat": 41.2966732,
    "lng": -96.0556455,
    "address": "9211 Sahler Street Omaha, NE 68134"
  },
  {
    "lat": 41.2454034,
    "lng": -96.2145048,
    "address": "1411 S 190th Plaza Omaha, NE 68130"
  },
  {
    "lat": 41.1178765,
    "lng": -95.98126889999999,
    "address": "4502 Leawood Dr Bellevue, NE 68133"
  },
  {
    "lat": 41.20136309999999,
    "lng": -96.03974389999999,
    "address": "8037 Main Street Ralston, NE 68127"
  },
  {
    "lat": 41.2297185,
    "lng": -96.08283759999999,
    "address": "3206 S 109 Street Omaha, NE 68144"
  },
  {
    "lat": 41.255032,
    "lng": -96.159773,
    "address": "15675 Howard Street Omaha, NE 68118"
  },
  {
    "lat": 41.2594884,
    "lng": -95.95978559999999,
    "address": "120 S 31st Ave #5410 Omaha, NE 68131"
  },
  {
    "lat": 41.119718,
    "lng": -96.028571,
    "address": "12704 S 75th Ave Papillion, NE 68046"
  },
  {
    "lat": 41.049045,
    "lng": -95.95738,
    "address": "2912 Lakeside Dr Plattsmouth, NE 68135"
  },
  {
    "lat": 41.1782713,
    "lng": -95.9369613,
    "address": "1105 Colorado St Bellevue, NE 68005"
  },
  {
    "lat": 41.2593404,
    "lng": -95.927219,
    "address": "105 S 9th Street, Unit 501 Omaha, NE 68102"
  },
  {
    "lat": 41.2443179,
    "lng": -95.96072579999999,
    "address": "1522 S 32nd Ave Omaha, NE 68105"
  },
  {
    "lat": 40.8178552,
    "lng": -96.58862599999999,
    "address": "9900 Crystal Water Circle Lincoln, NE 68527"
  },
  {
    "lat": 41.1405077,
    "lng": -96.0213976,
    "address": "1410 Cherry Tree Ln Papillion, NE 68133"
  },
  {
    "lat": 41.3099955,
    "lng": -96.08554339999999,
    "address": "11215 Ellison Ave Omaha, NE 68164"
  },
  {
    "lat": 41.2622541,
    "lng": -95.97326989999999,
    "address": "326 N 40th Street Omaha, NE 68131"
  },
  {
    "lat": 41.1439611,
    "lng": -96.1108208,
    "address": "12618 Glenn St Omaha, NE 68138"
  },
  {
    "lat": 41.3271701,
    "lng": -96.053968,
    "address": "9113 Black St Omaha, NE 68122"
  },
  {
    "lat": 41.2099032,
    "lng": -96.0721942,
    "address": "10305 N Street Omaha, NE 68127"
  },
  {
    "lat": 41.26620740000001,
    "lng": -95.9860527,
    "address": "4804 Webster St Omaha, NE 68132"
  },
  {
    "lat": 41.2893749,
    "lng": -96.01893249999999,
    "address": "6795 Emmet Street Omaha, NE 68104"
  },
  {
    "lat": 41.28352,
    "lng": -95.995933,
    "address": "2707 N 53rd Street Omaha, NE 68104"
  },
  {
    "lat": 41.0559781,
    "lng": -95.95384039999999,
    "address": "21018 Treasure Island Road Plattsmouth, NE 68048"
  },
  {
    "lat": 41.2267634,
    "lng": -96.03377950000001,
    "address": "3519 S 78th Street Omaha, NE 68124"
  },
  {
    "lat": 41.1982333,
    "lng": -96.18139959999999,
    "address": "17119 Y St Omaha, NE 68135"
  },
  {
    "lat": 41.294473,
    "lng": -96.1360126,
    "address": "14261 Sprague Circle Omaha, NE 68164"
  },
  {
    "lat": 41.2771272,
    "lng": -96.1903174,
    "address": "17610 Parker Plz Omaha, NE 68118"
  },
  {
    "lat": 41.2537027,
    "lng": -95.9363039,
    "address": "1502 Jones Street #209 Omaha, NE 68102"
  },
  {
    "lat": 41.2600453,
    "lng": -95.99711239999999,
    "address": "103 N 54th St Omaha, NE 68132"
  },
  {
    "lat": 41.3280061,
    "lng": -96.1474212,
    "address": "14905 Potter Street Bennington, NE 68007"
  },
  {
    "lat": 41.1914991,
    "lng": -96.093918,
    "address": "11649 Polk Street Omaha, NE 68137"
  },
  {
    "lat": 40.9242168,
    "lng": -95.8764108,
    "address": "9216 Talmadge Court Plattsmouth, NE 68048"
  },
  {
    "lat": 41.3207145,
    "lng": -96.1462401,
    "address": "6731 North 148th Street Omaha, NE 68116"
  },
  {
    "lat": 41.1755212,
    "lng": -95.98938860000001,
    "address": "8314 S 49th St Bellevue, NE 68157"
  },
  {
    "lat": 41.2158311,
    "lng": -96.18850959999999,
    "address": "17463 I St Omaha, NE 68135"
  },
  {
    "lat": 40.9275214,
    "lng": -96.52663899999999,
    "address": "11947 N 143rd St Waverly, NE 68462"
  },
  {
    "lat": 41.2368511,
    "lng": -96.05421,
    "address": "2330 S 91st St Omaha, NE 68124"
  },
  {
    "lat": 41.3313492,
    "lng": -96.0876263,
    "address": "11128 King St\nOmaha, NE 68142"
  },
  {
    "lat": 41.3016449,
    "lng": -96.2088215,
    "address": "4802 N 187th Ave Omaha, NE 68022"
  },
  {
    "lat": 41.1233994,
    "lng": -96.05193279999999,
    "address": "12410 S 89th Avenue Papillion NE, 68046"
  },
  {
    "lat": 41.1567003,
    "lng": -95.9262498,
    "address": "2915 Danielle Circle Bellevue, NE"
  },
  {
    "lat": 41.2461449,
    "lng": -95.9964887,
    "address": "5402 William St, Omaha, NE 68106"
  },
  {
    "lat": 41.2039356,
    "lng": -96.2072288,
    "address": "1730 S 22th Ave Elkhorn, NE 68022"
  },
  {
    "lat": 41.3271701,
    "lng": -96.053968,
    "address": "9113 Black Street, Omaha NE 68122"
  },
  {
    "lat": 41.2739284,
    "lng": -96.0803619,
    "address": "1515 N 107th Ave Omaha NE 68114"
  },
  {
    "lat": 40.8070111,
    "lng": -96.6450756,
    "address": "650 S 55 Street Lincoln, NE 68510"
  },
  {
    "lat": 41.2569786,
    "lng": -95.9373664,
    "address": "312 S 16th Street Omaha. NE 68102"
  }
];
